version: '3.8'

services:
  localstack:
    container_name: "local_aws_s3"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4572:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - './local_registry/dev:/tmp/registrations'
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - './.aws:/docker-entrypoint-initaws.d'
      - "./.aws/create-bucket.sh:/etc/localstack/init/ready.d/init-aws.sh"
  graphql-gateway:
    build:
      context: .
    depends_on:
      - "localstack"
    environment:
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - AWS_DEFAULT_REGION="us-west-2"
      - AWS_S3_BUCKETS_USEAST2_ENDPOINT=http://host.docker.internal:4572
      - AWS_S3_BUCKETS_USWEST2_ENDPOINT=http://host.docker.internal:4572
    ports:
      - 7000:7000

